package miniproject;

import java.sql.SQLException;
import java.util.Scanner;

public class UserThread extends Thread
{
Scanner sc = new Scanner(System.in);
	
	UserPojo p1;
	public UserThread(UserPojo u1)
	{
		this.p1=u1;
	}
	
	public void run()
	{
		try {
			ValidUser1(p1.getuName());
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	public void ValidUser1(String uName) throws SQLException
	{
		int ch2=0;
		do
		{
			System.out.println("You are user");
			System.out.println("----------Menu For User------------");
			System.out.println("1. Show All Items ");
			System.out.println("2. Select Item: ");
			System.out.println("3. Enter the Item you want to order: ");
			System.out.println("4. show the Bill generated by me ");
		
			
		
			System.out.println("Enter your choice as a User: ");
			ch2 = sc.nextInt();
			
			switch(ch2)
			{
			
				case 1:
				{
					
					System.out.println("-------All The Products Available in Hotel--------");
					ProductDao.displayProducts();
					break;
				}
				
				case 2:
				{
					
					System.out.println("Enter Product Id: ");
					int pId = sc.nextInt();
					ProductDao.searchProduct(pId);
					break;
				}
				
				case 3:
				{
					System.out.println("Enter Order Id");
					int oId = sc.nextInt();
					System.out.println("Enter quantity");
					int quantity = sc.nextInt();
					System.out.println("Enter User Id");
					int uId1 = sc.nextInt();
					System.out.println("Enter Product Id");
					int pId1 = sc.nextInt();
					
					OderPojo o = new OderPojo(oId,quantity,uId1,pId1);
					
					boolean flag = OrderDao.insertOrder(o);
					
					if(flag)
					{
						System.out.println("Book added successfully");
					}
					else
					{
						System.out.println("something went wrong please try again");
						
					}
					
					
					break;
				}
				case 4:
				{
					System.out.println("Enter User ID: ");
					int uId = sc.nextInt();
					System.out.println("Bill Genered by Me: ");
					OrderDao.getBill(uId);
					
					break;
				}
			
			
			
			
			
			
			
			
			
			
			
			
			
			}
			
			
		}
		while(ch2!=0);
		
		
	}

}
